export const arrayTypeProducts = [
    { typeProduct: 'all', btnName: 'Все книги' },
    { typeProduct: 'business', btnName: 'Бизнес-книги' },
    { typeProduct: 'detective', btnName: 'Детективы' },
    { typeProduct: 'children', btnName: 'Детские книги' },
    { typeProduct: 'foreign', btnName: 'Зарубежная литература' },
    { typeProduct: 'history', btnName: 'История' },
    { typeProduct: 'classic', btnName: 'Классическая литература' },
    { typeProduct: 'psychology', btnName: 'Книги по психологии' },
    { typeProduct: 'computers', btnName: 'Компьютерная литература' },
    { typeProduct: 'culture', btnName: 'Культура и искусство' },
    { typeProduct: 'science', btnName: 'Наука и образование' },
    { typeProduct: 'publicistic', btnName: 'Публицистическая литература' },
    { typeProduct: 'references', btnName: 'Справочники' },
    { typeProduct: 'scifi', btnName: 'Фантастика' },
    { typeProduct: 'humor', btnName: 'Юмористическая литература' },
]